name: UniHs
version: 0.0.1.0
github: "TimeTravelPenguin/UniHs"
license: MIT
author: "Phillip Smith"
maintainer: "TimeTravelPenguin@gmail.com"
copyright: "Copyright (c) 2022 Phillip Smith"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
synopsis: Maintain and create assessment template directories from templates
category: Application

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/TimeTravelPenguin/UniHs#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson < 2.2.1
  - aeson-pretty < 0.9
  - ansi-terminal < 1.1
  - bytestring < 0.12
  - containers < 0.7
  - colour <= 2.3.6
  - either < 5.1
  - extra < 1.8
  - filepath < 1.5
  - transformers < 0.6.2
  - lens < 5.3
  - matrix < 0.3.7
  - megaparsec < 9.5
  - mtl < 2.4
  - optparse-applicative < 0.19
  - path < 0.10
  - path-io < 1.9
  - pretty-simple < 4.2
  - QuickCheck < 2.15
  - safe < 0.4
  - text < 2.1
  - vector < 0.13.2

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - ImportQualifiedPost

executables:
  UniHs-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - UniHs

  UniHs-TUI-exe:
    main: Main.hs
    source-dirs: app-tui
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - UniHs

tests:
  UniHs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - UniHs
